language: python
python:
  - "3.6"
git:
  depth: 9999999
sudo: required
services:
  - docker
branches:
  only:
    - master
    - test
before_script:
  - sudo python3 -m pip install pytest flake8
  - flake8
  - pytest test_builder.py
  - docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD"
script: python3 build.py $TRAVIS_COMMIT
