version: '3'
services:
  ubuntu-dev-base-local:
    image: yoshwata/ubuntu-dev-base-local:bionic
    command: /bin/bash
    build:
      context: ../images/ubuntu-dev-base/
      args:
        USER: "yoshwata"
        UID: 1000
        GROUP: "users"
        GID: 1000
    volumes: &vol
      # work dir
      - ~/:/work
      # settings
      - ./.tmux.conf:~/.tmux.conf
      - ./.bash_history:~/.bash_history
      - ./.bash_profile:~/.bash_profile
      - ./.path:~/.path
      - ./.bash_prompt:~/.bash_prompt
      - ./.exports:~/.exports
      - ./.aliases:~/.aliases
      - ./.functions:~/.functions
      - ./.gitconfig.sh:~/.gitconfig.sh
      # secret settings
      - ./.extra:~/.extra
      - ./.kube:~/.kube
    working_dir: /work
  power-tmux-local:
    build:
      context: ../images/power-tmux
      args:
        FROM_IMG: ubuntu-dev-base-local
    image: yoshwata/power-tmux-local:bionic
    command: tmux new
    volumes: *vol
    working_dir: /work
  nvim-local:
    build:
      context: ../images/nvim
      args:
        FROM_IMG: power-tmux-local
    image: yoshwata/nvim-local:bionic
    command: tmux new
    volumes: *vol
    working_dir: /work
  nodejs-base-local:
    build:
      context: ../images/nodejs-dev/base
      args:
        FROM_IMG: nvim-local
    image: yoshwata/nodejs-base-local:bionic
    command: tmux new
    volumes: *vol
    working_dir: /work
  nodejs-local:
    build:
      context: ../images/nodejs-dev/dubnium
      args:
        FROM_IMG: nodejs-base-local
    image: yoshwata/nodejs-dev-10-local:bionic
    command: tmux new
    volumes: *vol
    working_dir: /work

