name: Docker Image CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish ubuntu-dev-base
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: yoshwata/ubuntu-dev-base
        workdir: images/ubuntu-dev-base
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        snapshot: "true"
        cache: "true"
    - name: Publish power-tmux
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: yoshwata/power-tmux
        workdir: images/power-tmux
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        snapshot: "true"
        cache: "true"
    - name: Publish nvim
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: yoshwata/nvim
        workdir: images/nvim
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        snapshot: "true"
        cache: "true"
    - name: Publish nodejs base
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: yoshwata/nodejs-dev-base
        workdir: images/nodejs-dev/base
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        snapshot: "true"
        cache: "true"
    - name: Publish nodejs 10
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: yoshwata/nodejs-dev-10
        workdir: images/nodejs-dev/dubnium
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        snapshot: "true"
        cache: "true"
